### ISSUE TITLE
Failure to compile Linux-x64. 'devicepixelratio was not declared in this scope'

### ISSUE THREAD

**Issue by tomw2005** [frankyeh/DSI-Studio#12]
I have tried compiling on Gentoo amd64 and ran into the following error:

"../src/opengl/glwidget.cpp:2097:79: error: devicePixelRatio was not declared in this scope
             QImage I1 = grabFrameBuffer().scaledToWidth(1024*devicePixelRatio());
Makefile:2126: recipe for target 'glwidget.o' failed"

Full output at [http://pastebin.com/2BQYC80W](http://pastebin.com/2BQYC80W)

I have installed all dependencies and upgraded my system to QT5 as described in the install guide. I have done everything except the Nvidia drivers step as I do not have Nvidia graphics. 

A similar issue with a different package that moved to QT5 can be found here: [http://forum.openscenegraph.org/viewtopic.php?t=13287](http://forum.openscenegraph.org/viewtopic.php?t=13287) Perhaps something similar to that solution is needed?

**Comment by frankyeh** [comment]
It seems that your compiler uses an older version of Qt, which does not
have devicePixelRatio() define. You may need to remove Qt completly and
reinstall it to see if it works out for you.

Alternatively, you may replace devicePixelRatio() by 1 to silence this
error, but I worry that the version problem may crash the program even if
you pass compilation.

Best regards,
Frank

**Comment by tomw2005** [comment]
Hi Frank,

It was my own error. Despite having installed QT 5.4.2 it needs to be called thusly in Gentoo:

    /usr/lib/qt5/bin/qmake ../src

Clearing the build directory and running that fixed the issue.

Relevant Gentoo wiki page: https://wiki.gentoo.org/wiki/Qt#Compiling_programs_that_use_qmake_and_need_Qt5

Kind regards,
Tom

**Comment by tomw2005** [comment]
Also worth noting that running qmake did not add the `-lboost_system` argument to the Makefile. I had to add it manually to get compilation to work.

**Comment by frankyeh** [comment]
Thanks for the information.
