### ISSUE TITLE
segmentation fault after running dsi_studio

### ISSUE THREAD

**Issue by zhuxiaoyao** [frankyeh/DSI-Studio#15]
Hi, Frank,

After we finally successfully installed DSI Studio on our server, we still seems to have the following issues. 

Issue 1: no pop-up window for fiber tracking on our server. 

Issue 2 : segmentation fault when running in command line and performing csf calibration. 
#dsi_studio --action=rec --source=data.src.gz --mask=nodif_brain_mask.nii.gz --method=4 --param0=1.25 --csf_calibration=1

we can run export and file format conversion using command line without a problem. we can perform reconstruction and csf calibration using GUI without a problem. If we don't perform csf calibration, we can run the reconstruction using command line:

dsi_studio --action=rec --source=data.src.gz --mask=nodif_brain_mask.nii.gz --method=4 --param0=1.25.

Any insights on this will be greatly appreciated. 

Regards
Lingjie

![123](https://cloud.githubusercontent.com/assets/23691035/21489939/78fc24b4-cc2a-11e6-9bc0-f39cbed3598a.png)

**Comment by frankyeh** [comment]
Hi Lingjie,

    Could you send me the SRC file to test the bug on my side? I will fix
the bug as soon as possible.

Best regards,
Frank

**Comment by zhuxiaoyao** [comment]
Hi, Frank,

Thanks for the reply. 

The SRC file as attached, anything additional required please let me know as well.

Thanks again and happy new year.

Regards
Lingjie
[src.zip](https://github.com/frankyeh/DSI-Studio/files/676572/src.zip)

**Comment by frankyeh** [comment]
Hi Lingjie,

    I meant the data.src.gz and nodif_brain_mask.nii.gz file that caused
the problem.

Best regards,
Frank

**Comment by zhuxiaoyao** [comment]
Hi, Frank,

Sorry for my obsess in the installation process.

The data.src.gz appears to be too big to be attached, so I included two subjects (added 1 and 2 respectively to differentiate them) in the following dropbox link:
https://www.dropbox.com/sh/8z21w0wjr8o0pu3/AAB9QocR0TyDNrXF1km91ZzDa?dl=0 

Thanks and Regards
Lingjie

**Comment by zhuxiaoyao** [comment]
Hi, Frank,

Any updates on this one? or if you need more information, let me know:)

Best regards
Lingjie

**Comment by frankyeh** [comment]
Hi Lingjie,

    Thanks for the reminder. I will let you know once I have a fix.

Best regards,
Frank

**Comment by frankyeh** [comment]
Hi Lingjie,

    I am sorry for my late reply. It seems that the bug only exists in
Linux system. I cannot get the same error in Windows command line. I tried
some fix in the most recent code modification and add some tracing output.
Please update DSI Studio at your side and test it to see if it works out
for you. If not, please attach the log output and I will do my best to find
out the cause again.

Best regards,
Frank
