### ISSUE TITLE
menubar in dicom_parser.ui not visible

### ISSUE THREAD

**Issue by sbaete** [frankyeh/DSI-Studio#16]
Dear Frank,

First of all, thank you for making and maintaining this great tool!
I compile DSIStudio on linux mint and ubuntu OS. I noticed that in the last versions, you made a menubar in the "Step1: Open Source Images"-menu (dicom_parser.ui). I can see it's there in Qt Creator, but it does not show up in the actual dialog when compiled.
Some googling led me to [this discussion](https://forum.qt.io/topic/7276/menu-not-showing-up-in-menubar/11). Inspired by that post, I looked and saw the nativeMenuBar-field was already false. However, it turns out that if you turn the defaultUp-field on and recompile, the menubar does show up. That solved my problem. I'm not sure how it will affect compilation on other platforms, but you might consider including it in the code if you want.

Best regards,

Steven

**Comment by frankyeh** [comment]
Hi Steven,

    Thank you for the information and the solution to this problem.

    I always use the command line "qmake" to build DSI Studio, and it can
avoid the problems from Qt Creator.

Thanks,
Frank

**Comment by sbaete** [comment]
Hey Frank,

Thank you for getting back to me.
I also use qmake in the command line. I just use qt-creator to solve the
occasional bug.
I think my issue might be due to some minor incompatibility between qt on
the different operating systems.

See you in Hawaii?

Best regards,

Steven
