### ISSUE TITLE
Compatibility with Trackvis

### ISSUE THREAD

**Issue by takhs91** [frankyeh/DSI-Studio#17]
Hi,
I tried to load some .trk file and an fa file both produced with dsi studio(built from masre branch) into Trackvis and in multiple cases I tried the orientation was wrong.

I checked one of one trk file produced from dsi-studio and one produced from the Trackvis's diffusion toolkit using the `nibabel.streamlines` interface.

While of course the actual fiber tracts where not the same to compare the main differences was that you were using voxel_order=LPS instead of RAS used in trackvis and of course the related differences (first two diagonals of the affine are negative, fibers first two points are negative etc.).

If both software were using the same conventions I would expect that they could inter operate.

May I ask what  are the conventions used in dsi-studio regarding to coordinate systems when exporting/importg trk files etc?

**Comment by frankyeh** [comment]
Hi,

   DSI Studio uses LPS and thus the affine matrix is also different. DSI
Studio can also take RAS and will apply rotation to it. I am not sure if
TrackVis can take LPS, and it seems that this is the problem here.

Best regards,
Frank
.

**Comment by takhs91** [comment]
Thanks for your answer! 
Something more to clarify. Do you use LPS+ regarding the voxel indexing , do you consider the world coordinates being in LPS+ or both?
And what about the exported lets say Fa map or some tracks. Are they following the internal conventions or transformed to something else?(maybe to what the original input was)

**Comment by frankyeh** [comment]
Both, the output is also LPS.

**Comment by takhs91** [comment]
Isn't it required for the NIfti files to have a RAS+ world coordinate system ? I would expect in that case the exported FA map to have RAS+ world system and maybe LPS voxel indexing. Do I assume wrong?
Thanks for the very quick replies

**Comment by frankyeh** [comment]
The srow can be used to handle this condition. The voxel index can still
be LPS in nifti if the srow is adequately formulated.

**Comment by takhs91** [comment]
OK yes I understand that. So the voxel indexing will be LPSbutt the world system of the NIFTI export will be in RAS+ as defined by the standard right?

**Comment by frankyeh** [comment]
Yes.

**Comment by takhs91** [comment]
Ok thanks fro the information. I will look it up more and if I figure things out I may come back to report any findings
