### ISSUE TITLE
B-tables in Philips MR-enhanced DICOM files

### ISSUE THREAD

**Issue by jsgillen1** [frankyeh/DSI-Studio#18]
Hi,
We have been trying to read MR enhanced DICOM using DSI studio and it doesn't recognize the b-table stored in the DICOM header - dialog box with "Cannot find b-table from the header. You may need to load an external b-table". I had been using the November 10 2015 build. 

I tried updating to the latest Oct 12 2017 and it won't read the enhanced MR DICOM files at all - returns "Invalid file format". It also always shows a dialog box with "Failed to load template file at" but this doesn't seem to stop it from running.

I downloaded the source and built on my Mac which reads the file but no b-tables found (like the 2015 build). I looked at the code (and I am no pro at C++ - old C programmer), but I did see that the sequences in the DICOM header (Type SQ object) are read in as a whole and the items are not processed. The Per-Frame Functional Groups sequence contains all the info about individual images and this is where the b-tables are stored. I added some code to cause this sequence (and any others) to be processed. For Philips enhanced-MR files (at least) the b-table is now found. 

Reading sequences this way could cause some unexpected problems in some DICOM files. For instance, sometimes there is a sequence containing information about the scan used to prescribe this scan. This sequence can contain DICOM fields for imaging parameters of this prescribing sequence. But since my change just reads the sequence items inline there's no way to distinguish these from the current scan's parameters.

I have attached the modified dicom.hpp from the image/io directory for you to look at.
[dicom.hpp.zip](https://github.com/frankyeh/DSI-Studio/files/1451535/dicom.hpp.zip)

Best regards,
Joe

**Comment by frankyeh** [comment]
Much appreciated and I will check out the modification and update DSI
Studio accordingly.

Best regards,
Frank

**Comment by frankyeh** [comment]
The commit done today solved this issue.
