### ISSUE TITLE
CentOS7 build from tip of master

### ISSUE THREAD

**Issue by buildqa** [frankyeh/DSI-Studio#20]
Hello, 

I checked out the latest source for DSI-Studio, then under DSI-Studio got the TIPL archive and renamed /TIPL to ./image.  I installed the devtoolst-4 and enabled it so my bash shell environment is set to use gcc/g++ 5.3.1 compilers.  (Prior to that I was getting gcc 4 compilers).  I see there is a script, build_linux_red_hat.sh, at the top of the tree so I have been using this.  It generates a Makefile, and then runs the build (and also does that fix I think you mentioned elsewhere in the online documentation).  But ultimately, whether or not I use gcc 4 or 5 compilers, I end up with a segfault.  I got a bit further along with the build using the gcc 5 compilers, but still segfaulted eventually at,
./image/ml/cnn.hpp: At global scope:
./image/ml/cnn.hpp:1119:5: internal compiler error: Segmentation fault

I could try a newer devtoolset with gcc 6 compilers, but I thought I would first post this to see if you could advise about anything I am missing to remedy this. (I am also using qt5 I believe, or at least that is where my qmake comes from).  Thanks for any info/updates.

**Comment by frankyeh** [comment]
Hi,

     I am sorry that I have no clue about why this error happens. gcc4 is
not able to compile the code for sure, but gcc 5 should be able to work. It
seems to me that the only choice here is to test gcc6.

Best regards,
Frank
