### ISSUE TITLE
Compilation errors with CentOS 6.9

### ISSUE THREAD

**Issue by singhswg** [frankyeh/DSI-Studio#21]
Hi Frank

I am getting the following error from which I can't move forward. I am pretty sure that all header files are available in the correct location and the function calls are also right. Could you help me out? I downloaded the repository on Feb 19th, 2018.

Many thanks,
Singh
---------------------------------------------------------------------------------------------------------------------------

../src/tracking/tract/tracttablewidget.cpp: In member function 'void TractTableWidget::save_profile()':
../src/tracking/tract/tracttablewidget.cpp:510:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(currentRow() >= tract_models.size())
                     ^
../src/tracking/tract/tracttablewidget.cpp: In member function 'void TractTableWidget::deep_learning_train()':
../src/tracking/tract/tracttablewidget.cpp:573:61: **error**: no matching function for call to 'image::ml::network_data<float, unsigned char>::save_to_file(const char*)'
     cnn.cnn_data.save_to_file(filename.toStdString().c_str());
                                                             ^
In file included from ../src/image/image.hpp:80:0,
                 from ../src/tracking/tract/tracttablewidget.h:7,
                 from ../src/tracking/tract/tracttablewidget.cpp:8:
../src/image/ml/cnn.hpp:807:10: note: candidate: template<class io_type> bool image::ml::network_data<value_type, label_type>::save_to_file(const char*) const [with io_type = io_type; value_type = float; label_type = unsigned char]
     bool save_to_file(const char* file_name) const
          ^
../src/image/ml/cnn.hpp:807:10: note:   template argument deduction/substitution failed:
../src/tracking/tract/tracttablewidget.cpp:573:61: note:   couldn't deduce template parameter 'io_type'
     cnn.cnn_data.save_to_file(filename.toStdString().c_str());

**Comment by frankyeh** [comment]
The TIPL source code needs to be updated.

Let me know if this works for you.

Best regards
Frank

**Comment by singhswg** [comment]
Hi Frank

I still get the same error with the updates TIPL source code. I wonder what's wrong...

Best
Singh

**Comment by frankyeh** [comment]
Hi Singh,

    Are you getting the same error message? Could you post it again if the
message is different?

Best regards,
Frank

**Comment by singhswg** [comment]
Hi Frank,

Yes it's the same error message. Everything seems to be in their correct paths as the installation says. Is there any other dependency?

Best
Singh

**Comment by frankyeh** [comment]
Hi Singh

     What is the version date of your TIPL library and DSI studio?

Best regards
Frank

**Comment by singhswg** [comment]
Hi

TIPL - 03/21/2018
DSI studio - 02/15/2018

To give you more info, this is what I am doing,

Inside "src" directory, unzipped All TIPL-master files to directory "image"
Inside "src" directory, all boost files in directory "boost"

Created Makefile in "build" folder using "$ qmake ../src/"
Next step -> $ make

I am working with gcc-7.2.0

Best,
Singh

**Comment by frankyeh** [comment]
Hi Singh,

    You may need to use a more recent version of DSI Studio source code. It
seems that there is a mismatch between these two versions.

    Let me know if there is still an error in compiling the code.

Best regards,
Frank
