### ISSUE TITLE
Problem in fiber tracking step

### ISSUE THREAD

**Issue by Wangziqi1122** [frankyeh/DSI-Studio#22]
Hello frankyeh:
    I use dsi_studio for studying. But I found a problem on “Fiber Tracking” step. I used step1 to create .src file after I compiled dsi_studio. And in step2, I reconstruct DWI space to T1W. Then there is something wrong in step3, when I need to draw an area in region window. The polygon I’ve down will not be completely shown if I use free-hand drawing or polygon drawing. But if I use rectangle drawing, everything is OK.
![dsi-problem](https://user-images.githubusercontent.com/30174267/37631142-441c8b30-2c23-11e8-8ec5-f3bbb1f3b8d3.png)
    The left picture is the area I want, but the final view is the right picture.
    Can you help me to find a way of dealing with this problem? I can provide the fib file I’m using if you want.

**Comment by frankyeh** [comment]
It is a bug in DSI Studio, and I will do my best to fix it.

Could you please send me the full screenshot of the entire DSI Studio
window?

I may also need the build date of your DSI Studio.

Thanks you,
Frank

**Comment by Wangziqi1122** [comment]
I'm sorry I'm refused to send you the build data by my teacher.... But I can send the full screenshot. And I want to ask if the .fib file include the personal information or the hospital information about the patient? Maybe I can persuade my teacher to send the .fib file to you.
This is my screenshot.  I hope that'll be helpful
![dsi_full](https://user-images.githubusercontent.com/30174267/37632110-8fa692cc-2c27-11e8-82ef-d1cb8718d63c.png)

Thank you

**Comment by frankyeh** [comment]
The screenshot is good enough for me to fix the bug. You don't have to send
me the file. (The SRC and FIB file are de-identified as long as the file
name does not contain sensitive information, by the way).

I will let you know once there is an update.

Best regards,
Frank

**Comment by Wangziqi1122** [comment]
Thank you, I will wait for the update

**Comment by frankyeh** [comment]
Could you tell me the version (date) of DSI Studio you are using?

**Comment by Wangziqi1122** [comment]
The version I'm using is ddfd9ecfab7600c6206c5dce88491b95c5accc48(2017/10/22). And I also tested on the latest version

**Comment by Wangziqi1122** [comment]
I have tested and everything is OK. Thank you very much!
