### ISSUE TITLE
Problem in setting up ROIs for connectivity matrix

### ISSUE THREAD

**Issue by yingqiuz** [frankyeh/DSI-Studio#23]
Hello Dr. Yeh

When I was trying to construct a connectivity matrix in native space, DSI studio fails to read the file list text file with ROI file name (one name per row):

The command was
`dsi_studio --action=trk --source="/path/to/source.fib.gz" --method=0 --seed="/path/to/seed.nii.gz" --roa="/path/to/roa1.nii.gz" --roa2="/path/to/roa2.nii.gz" --otsu_threshold=0.7 --min_length=20 --max_length=400 --step_size=.5 --turning_angle=55 --fiber_count=100000 --seed_count=5000000 --connectivity=/path/to/roi_list.txt --connectivity_type=pass --connectivity_value=count,ncount,mean_length --output=no_file`

and the roi_list.txt file was
```
seed1.nii.gz
seed2.nii.gz
seed3.nii.gz
seed4.nii.gz
```
And the output was:
```
DSI Studio Feb  3 2018, Fang-Cheng Yeh
loading /path/to/source...
fiber_count=100000
read region from /path/to/roa1.nii.gz
roa=/path/to/roa1.nii.gz
read region from /path/to/roa2.nii.gz
roa2=/path/to/roa2.nii.gz
read region from /path/to/seed.nii.gz
seed=/path/to/seed.nii.gz
turning_angle=55
fa_threshold=0.0608798
step_size=0.5
smoothing=1
min_length=20
max_length=400
tracking_method=0
initial direction=0
interpolation=0
voxelwise=0
thread_count=12
start tracking.
 A multishell diffusion scheme was used, and the b-values were 2000 ,3005 and 1990 s/mm2. The number of diffusion sampling directions were 90, 90, and 90, respectively. The in-plane resolution was 1.25 mm. The slice thickness was 1.25 mm. The diffusion data were reconstructed using generalized q-sampling imaging (Yeh et al., IEEE TMI, ;29(9):1626-35, 2010) with a diffusion sampling length ratio of 1. The restricted diffusion was quantified using restricted diffusion imaging (Yeh et al., MRM, 77:603â612 (2017)). A deterministic fiber tracking algorithm (Yeh et al., PLoS ONE 8(11): e80713) was used. An ROA was placed at /path/to/roa1.nii.gz (49,89,63) with a volume size of 7.6e+05 mm cubic. An ROA was placed at /path/to/roa2.nii.gz (88,1.2e+02,29) with a volume size of 6.7e+04 mm cubic. A seeding region was placed at /path/to/seed.nii.gz (92,48,45) with a volume size of 1.2e+04 mm cubic. The angular threshold was 55 degrees. The step size was 0.5 mm. The anisotropy threshold was 0.0608798. The fiber trajectories were smoothed by averaging the propagation direction with a percentage of the previous direction. The percentage was randomly selected from 0% to 95%. Tracks with length shorter than 20 or longer than 400 mm were discarded. A total of 100000 tracts were calculated.
finished tracking.
a total of 100000 tracts are generated
loading /path/to/roi_list.txt
/path/to/roi_list.txt is used as an MNI space ROI.
Subject normalization to MNI space.
loading roi_list...
program terminated due to exception:Cannot load atlas file
```
I wonder 1) why roi_list was still taken as an MNI space ROI  2) why dsi_studio failed to load the txt file roi_list.txt?

Thanks you for your time and efforts. It would be more than appreciated if you could help me solve this problem.

**Comment by frankyeh** [comment]
Please update DSI Studio and see if it works for you.

**Comment by yingqiuz** [comment]
Thanks for your reply. I installed DSI studio on Feb 3rd 2018. Is it the newest version?

Thanks again.

On Apr 19, 2018, at 1:37 AM, frankyeh <notifications@github.com<mailto:notifications@github.com>> wrote:

Please update DSI Studio and see if it works for you.

**Comment by yingqiuz** [comment]
Problem solved after updating DSI studio. Thanks a lot
