### ISSUE TITLE
How to generate whole_brain.nii.gz from src file?

### ISSUE THREAD

**Issue by lidh15** [frankyeh/DSI-Studio#24]
I want to get whole brain seeding results and I see it is really easy to do this in GUI, but I have a batch processing task so I need command line tool.
![image](https://user-images.githubusercontent.com/14806954/42746566-f71d05fe-890a-11e8-8b2e-3651a5b0022a.png)
In command line I need whole_brain.nii for --seed as shown above, how can I get it?
Thanks.

**Comment by frankyeh** [comment]
If --seed is not assigned, then DSI Studio will use whole brain seeding.

**Comment by lidh15** [comment]
Thanks
