### ISSUE TITLE
Fail to use parameter id in command line

### ISSUE THREAD

**Issue by lidh15** [frankyeh/DSI-Studio#25]
I tried to use the method shown in the documentation using a parameter id to set the parameters, but it kept using default parameters.
![image](https://user-images.githubusercontent.com/14806954/42813298-1ec470b8-89f3-11e8-9ce3-67919157cee6.png)
I wonder what the problem is.
And I see we can export track parameters in GUI to .ini setting file, can I use it in command line?

**Comment by frankyeh** [comment]
It could be that you are using an older version of DSI Studio. Please
update it to see if it works.

**Comment by lidh15** [comment]
Well, I think I'm using the newest version, I downloaded Windows version from Google Drive 20 days ago.

**Comment by frankyeh** [comment]
Could you post the command here?

**Comment by lidh15** [comment]
$ dsi_studio --action=trk --source=WANG_XUANYI.src.gz.dti.fib.gz --parameter_CDCCCC3D9A99193Fb803Fcb803FbF041b964340420Feba --output=test.trk.gz --export=stat

**Comment by lidh15** [comment]
Thank you for your help, in fact I noticed several typos in the documentation, but most of them are nothing important, only this one is really confusing.
