### ISSUE TITLE
Diameter in nii file

### ISSUE THREAD

**Issue by Wangziqi1122** [frankyeh/DSI-Studio#27]
I do "Fiber Tracking" and set diameter for a better visual experience. I want to know is there any way to change diameter of tracking in nii file I saved?

**Comment by frankyeh** [comment]
In the right upper corner window, under [Track rendering] option there is
an item for controlling the diameter.

Hope this helps.
Frank

**Comment by Wangziqi1122** [comment]
Thank you and I have solved this problem!
