### ISSUE TITLE
lambda function in dwi_sort needs const parameters

### ISSUE THREAD

**Issue by SyamGadde** [frankyeh/DSI-Studio#28]
In:

https://github.com/frankyeh/DSI-Studio/blob/44b4063db6dfed4fd51f523c1a0203422e375852/dicom/dwi_header.cpp#L303

adding ``const`` before both arguments allows it to compile on gcc 4.8.5 (on Scientific Linux 7.x).

**Comment by frankyeh** [comment]
fixed

**Comment by frankyeh** [comment]
Thanks. It is done!
