### ISSUE TITLE
Is it possible to add gpu acceleration for fiber tracking?

### ISSUE THREAD

**Issue by lidh15** [frankyeh/DSI-Studio#29]
I have been using DSI studio for a while, though its performance is fantastic, it is not fast enough when tracking fibers with a huge seeds number. Is it possible to make this task parallel on gpu?

**Comment by frankyeh** [comment]
Fiber tracking is a recursive computation that cannot be benefited much by
gpu. The current version can make use of multicore CPU.

Best
Frank
