### ISSUE TITLE
[Command Line Tool] dt_threshold

### ISSUE THREAD

**Issue by pykao** [frankyeh/DSI-Studio#31]
Dear Professor Yeh,

I just download the latest version of DSI Studio. I am using the command line tool to track the fibers but I found there is one more parameter called dt_threshold=0. This parameter is not mentioned in your official DSI studio website. Can you please explain what is this parameter about?

Best,
Po-Yu Kao

**Comment by frankyeh** [comment]
Hi Poyu,

     It is for a testing method, and details will be documented once the
method is ready.

Best regards
Frank
