### ISSUE TITLE
Doesn't work anymore in cmd

### ISSUE THREAD

**Issue by lidh15** [frankyeh/DSI-Studio#33]
In the past several months I have been using the software.
But maybe due to some exchanges caused by Windows update it seems that the software doesn't work anymore and return at once without any information when I call "dsi_sudio --action=src --source=a --output=a.src.gz" or any other command.
If I try "dsi_studio", the gui shows and works well, but I gotta piles of data so I cannot use gui to deal with them one by one.
Do you have any clues about how to solve this problem?
Thanks

**Comment by frankyeh** [comment]
Is there any output from the command? (crash or error?)
 If there is still no clue, you may send me one or two sample folder and I
will fix it as soon as possible.
Frank

**Comment by frankyeh** [comment]
BTW, the GUI also supports batch processing, and you may not need to use
the command line:
(check out step 1a or step 1b)
http://dsi-studio.labsolver.org/Manual/create-a-connectometry-database#TOC-STEP1b:-Batch-create-the-SRC-files

**Comment by lidh15** [comment]
Thanks, I'm gonna try batch processing via GUI, the reason I don't like to use it is that my data are saved in a mess with lots of non-related data in the same directory, they may need some reorganization.

**Comment by lidh15** [comment]
I can generate the fiber file with batch processing but I cannot track them all in a batch, so I still have to solve the problem.
One of the data I'm using is [here](https://drive.google.com/open?id=1QtAqQK4zELHYU3XEefxpW7qPQPPl3Uun), the command is 

'dsi_studio --action=trk --seed_count=1000000 --min_length=30 --max_length=300 --output=no_file --export=stat --source=20190103_M004Y_DUZEHONG.src.gz.dti.fib.gz' 

and it returns at once without any output information, neither error nor warning.

**Comment by frankyeh** [comment]
which operating system are you using?

**Comment by lidh15** [comment]
Windows 10

**Comment by frankyeh** [comment]
run  dsi_studio --action=trk --seed_count=1000000 --min_length=30
--max_length=300 --output=no_file --export=stat
--source=20190103_M004Y_DUZEHONG.src.gz.dti.fib.gz > log.txt

and check if there is any message in log.txt ?

**Comment by lidh15** [comment]
Well, thanks for the log file, I found the problem. The new data I am processing have white spaces in their path. Though they were parsing properly in my python script, they broke into pieces when put into command line.
Now it's solved, thanks a lot.
