### ISSUE TITLE
Installation issue, Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jimcost** [frankyeh/DSI-Studio#34]
Hi Frank,

During the `make` step, I continue to run into the error concerning `regiontablewidget.o`. Here is the last few lines from `make`

```
In file included from ./tipl/morphology/morphology.hpp:7:0,
                 from ./tipl/tipl.hpp:32,
                 from tracking/region/Regions.h:7,
                 from tracking/region/regiontablewidget.h:7,
                 from tracking/region/regiontablewidget.cpp:10:
./tipl/numerical/basic_op.hpp: In instantiation of ‘void tipl::histogram(const ImageType&, std::vector<unsigned int>&, typename ImageType::value_type, typename ImageType::value_type, unsigned int) [with ImageType = tipl::const_pointer_image<float, 3>; typename ImageType::value_type = float]’:
./tipl/segmentation/otsu.hpp:17:14:   required from ‘float tipl::segmentation::otsu_threshold(const ImageType&) [with ImageType = tipl::const_pointer_image<float, 3>]’
tracking/region/regiontablewidget.cpp:1238:60:   required from here
./tipl/numerical/basic_op.hpp:896:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if(index >= hist.size())
            ~~~~~~^~~~~~~~~~~~~~
./tipl/numerical/basic_op.hpp: In instantiation of ‘void tipl::change_endian(type&) [with type = long int]’:
./tipl/io/nifti.hpp:441:22:   required from ‘void tipl::io::nifti_base<input_interface, output_interface>::convert_to_small_endian2() [with input_interface = gz_istream; output_interface = gz_ostream]’
./tipl/io/nifti.hpp:508:41:   required from ‘bool tipl::io::nifti_base<input_interface, output_interface>::load_from_file(const char_type*) [with char_type = char; input_interface = gz_istream; output_interface = gz_ostream]’
tracking/region/regiontablewidget.cpp:528:63:   required from here
./tipl/numerical/basic_op.hpp:944:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (char i = 0; i < sizeof(type); ++i,--pdata)
                      ~~^~~~~~~~~
./tipl/numerical/basic_op.hpp:945:17: warning: array subscript has type ‘char’ [-Wchar-subscripts]
         temp[i] = *pdata;
In file included from ./libs/tracking/tracking_method.hpp:11:0,
                 from ./libs/tracking/tracking_thread.hpp:9,
                 from tracking/region/regiontablewidget.cpp:17:
./libs/tracking/basic_process.hpp: In instantiation of ‘void LocateVoxel::operator()(method&) [with method = TrackingMethod]’:
./libs/tracking/tracking_method.hpp:211:18:   required from ‘void TrackingMethod::operator()(Process) [with Process = LocateVoxel]’
/usr/include/boost/mpl/for_each.hpp:78:26:   required from ‘static void boost::mpl::aux::for_each_impl<false>::execute(Iterator*, LastIterator*, TransformFunc*, F) [with Iterator = boost::mpl::v_iter<boost::mpl::vector<LocateVoxel>, 0>; LastIterator = boost::mpl::v_iter<boost::mpl::vector<LocateVoxel>, 1>; TransformFunc = boost::mpl::identity<mpl_::na>; F = boost::reference_wrapper<TrackingMethod>]’
/usr/include/boost/mpl/for_each.hpp:105:18:   required from ‘void boost::mpl::for_each(F, Sequence*, TransformOp*) [with Sequence = boost::mpl::vector<LocateVoxel>; TransformOp = boost::mpl::identity<mpl_::na>; F = boost::reference_wrapper<TrackingMethod>]’
/usr/include/boost/mpl/for_each.hpp:118:46:   required from ‘void boost::mpl::for_each(F, Sequence*) [with Sequence = boost::mpl::vector<LocateVoxel>; F = boost::reference_wrapper<TrackingMethod>]’
./libs/tracking/tracking_method.hpp:216:42:   required from ‘void TrackingMethod::tracking(ProcessList) [with ProcessList = boost::mpl::vector<LocateVoxel>]’
./libs/tracking/tracking_method.hpp:248:13:   required from ‘bool TrackingMethod::start_tracking(bool) [with ProcessList = boost::mpl::vector<LocateVoxel>]’
./libs/tracking/tracking_method.hpp:374:57:   required from here
./libs/tracking/basic_process.hpp:45:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(char i = 0;i < next_voxels_index.size();++i)
                        ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:3141: recipe for target 'regiontablewidget.o' failed
make: *** [regiontablewidget.o] Error 1
```

Any ideas? I'm using 7.4.0 version of `gcc` and `g++` but have received the error using version 5 as well (following the instructions in http://www.nemotos.net/?p=1878).

**Comment by frankyeh** [comment]
Could you post the "error" message? (search "error") The last few ones are
warnings unrelated to the compilation error.

**Comment by jimcost** [comment]
Hi Frank! Here you are:
```
../src/tracking/region/regiontablewidget.cpp: In member function ‘void RegionTableWidget::show_statistics()’:
../src/tracking/region/regiontablewidget.cpp:1037:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(currentRow() >= regions.size())
        ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
../src/tracking/region/regiontablewidget.cpp: In member function ‘void RegionTableWidget::do_action(QString, size_t)’:
../src/tracking/region/regiontablewidget.cpp:1222:56: error: no matching function for call to ‘QInputDialog::getDouble(RegionTableWidget*, const char [11], const char [30], double, double, double, int, bool*, Qt::WindowFlags, double)’
                     0.0,1.0,1,&ok,Qt::WindowFlags(),0.1);
                                                        ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QInputDialog:1:0,
                 from ../src/tracking/region/regiontablewidget.cpp:3:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qinputdialog.h:178:19: note: candidate: static double QInputDialog::getDouble(QWidget*, const QString&, const QString&, double, double, double, int, bool*, Qt::WindowFlags)
     static double getDouble(QWidget *parent, const QString &title, const QString &label, double value = 0,

```

**Comment by frankyeh** [comment]
It is a Qt version problem. Do you have  Qt. 5.12.2 installed?
Frank

**Comment by jimcost** [comment]
I did/do not have Qt 5.12.2 installed. I was able to install Qt 5.12.2 and able to build DSI Studio from the source code. But when executing `dsi_studio` I received an error about plugins for a library:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
```
I gave up and instead copied a previously compiled version.

Ultimately, I believe my problem was installed a new version of Qt and then forcing the system only to recognize the new version (with the libraries and dependencies appropriately linked).

**Comment by frankyeh** [comment]
A quick google of this error gave me this:
https://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

Hope it works.
Frank

**Comment by kirandhakal** [comment]
Dear Frank, could you please help me 
I got the following error during make step (Step 7 in http://www.nemotos.net/?p=1878) while compiling dsi studio in Ubuntu 18:04 LTS.
Error:
Makefile:5302: recipe for target 'group_connectometry.o' failed
make: *** [group_connectometry.o] Error 1
===== "Error" message  ==========
../src/connectometry/group_connectometry.cpp: In member function ‘void group_connectometry::show_fdr_report()’:
../src/connectometry/group_connectometry.cpp:168:60: error: ‘class QtCharts::QValueAxis’ has no member named ‘setTickType’
     ((QValueAxis*)fdr_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                            ^
../src/connectometry/group_connectometry.cpp:168:72: error: ‘TicksDynamic’ is not a member of ‘QtCharts::QValueAxis’
     ((QValueAxis*)fdr_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                                        ^
../src/connectometry/group_connectometry.cpp:169:60: error: ‘class QtCharts::QValueAxis’ has no member named ‘setTickInterval’
     ((QValueAxis*)fdr_chart->axes(Qt::Horizontal).back())->setTickInterval(10);
                                                            ^
../src/connectometry/group_connectometry.cpp: In member function ‘void group_connectometry::show_report()’:
../src/connectometry/group_connectometry.cpp:197:65: error: ‘class QtCharts::QValueAxis’ has no member named ‘setTickType’
     ((QValueAxis*)null_pos_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                                 ^
../src/connectometry/group_connectometry.cpp:197:77: error: ‘TicksDynamic’ is not a member of ‘QtCharts::QValueAxis’
     ((QValueAxis*)null_pos_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                                             ^
../src/connectometry/group_connectometry.cpp:198:65: error: ‘class QtCharts::QValueAxis’ has no member named ‘setTickInterval’
     ((QValueAxis*)null_pos_chart->axes(Qt::Horizontal).back())->setTickInterval(10);
                                                                 ^
../src/connectometry/group_connectometry.cpp:199:65: error: ‘class QtCharts::QValueAxis’ has no member named ‘setTickType’
     ((QValueAxis*)null_neg_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                                 ^
../src/connectometry/group_connectometry.cpp:199:77: error: ‘TicksDynamic’ is not a member of ‘QtCharts::QValueAxis’
     ((QValueAxis*)null_neg_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                                             ^
../src/connectometry/group_connectometry.cpp:200:65: error: ‘class QtCharts::QValueAxis’ has no member named ‘setTickInterval’
     ((QValueAxis*)null_neg_chart->axes(Qt::Horizontal).back())->setTickInterval(10);
                                                                 ^
../src/connectometry/group_connectometry.cpp: In function ‘void fill_demo_table(const connectometry_db&, QTableWidget*)’:
../src/connectometry/group_connectometry.cpp:238:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0;i < db.titles.size();++i)

**Comment by frankyeh** [comment]
It seems that your Qt does not have Qtchart. You may try the following:

sudo apt install libqt5charts5-dev

**Comment by kirandhakal** [comment]
I still got the same error.

**Comment by frankyeh** [comment]
The error suggests that the QtChart class in the Qt does not fit with
the one assumed by DSI Studio (Qt 5.12.2).

A final solution is to download the Qt 5.12.2 source code and compile
it to make sure that it is the right version.

Best regards,
Frank

**Comment by kirandhakal** [comment]
I have downloaded Qt 5.12.2 and compiled it. This folder is in my home directory where dsistudio is. 
When I check >qmake --version, it is showing  QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
And, looks like  "Makefile" within Home/dsistudio/build is still looking for Qt 5.9.5
(Makefile for building: dsi_studio
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  ../src/dsi_studio.pro)
So, could you please guide me what should I do next, where to put recent  Qt 5.12.2. 
And another confusion is about the recent dsi version, since I have Qt 5.9.5 in Makefile, does this means I don't have the latest one?

**Comment by frankyeh** [comment]
You would need to remove/update the Makefile using the new qmake in Qt
5.12.2.

Did you install Qt 5.9 previously?

**Comment by kirandhakal** [comment]
No, I didn't install 5.9

Are there any specific steps/ command to remove/update the Makefile??

**Comment by frankyeh** [comment]
run qmake to create the Makefile.

**Comment by willgpaik** [comment]
Hi Frank,  
I have the same Qt issue on Ubuntu 18.04. Do I have to have Qt 5.12.2? Qt 5.12.2 just came out only few months ago and it is not provided by all Linux distros. I'm not sure why DSI Studio requires to have the latest Qt. Can you at least tell me which commit can be compatible with older version of Qt? I prefer not to build Qt manually just for it.

**Comment by frankyeh** [comment]
The March version is still based on Qt 4. Sorry for the inconvenience.
Frank

**Comment by willgpaik** [comment]
Frank,  
Thanks for the information. I'll try to build March version.

**Comment by frankyeh** [comment]
One of the DSI Studio users solved this issue, and here's the approach
they tested.

1. Download the binary package from https://www.qt.io/offline-installers
2. Ensure that the default path to QT was for version 5.12 and not any
other version.
