### ISSUE TITLE
'make' failing: sqrtf is not a member of std

### ISSUE THREAD

**Issue by diffuze** [frankyeh/DSI-Studio#36]
Not sure if others have had issues with compiling dsi-studio on Linux. Running 'make' gave the following error:

'sqrtf is not a member of 'std''
[make_dsi_studio_output.txt](https://github.com/frankyeh/DSI-Studio/files/3397590/make_dsi_studio_output.txt)

I have attached the full output of 'make'. It doesn't like sqrtf() being called as std::sqrtf().

After trying several things (including different compilers), it seemed the only way to fix it was to rename std::sqrtf to sqrtf across all .cpp/.hpp files in src. The same had to be done for expf, cosf, and acosf. After doing so, running 'make' then worked fine.

Maybe others have had the same issue. Older and newer gcc versions gave the same issue.

System:
Ubuntu 18.04 LTS
gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
g++ (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Using Qt version 5.12.4

**Comment by frankyeh** [comment]
Thanks for reporting this issue. I will revise accordingly.

>
