### ISSUE TITLE
DSI make error

### ISSUE THREAD

**Issue by DoctorYe** [frankyeh/DSI-Studio#38]
System: ubuntu 18
gcc: v5.5
g++: v5.5
Error message shown below.
[Make.log](https://github.com/frankyeh/DSI-Studio/files/3732126/Make.log)
The out put of make script attached.

`connectometry/nn_connectometry_analysis.cpp:204:88: error: no matching function for call to ‘data_fold_for_cv(tipl::ml::network_data<float>&, std::vector<tipl::ml::network_data_proxy<float> >&, std::vector<tipl::ml::network_data_proxy<float> >&, size_t&, bool&)’
         tipl::ml::data_fold_for_cv(fp_data,train_data,test_data,cv_fold,stratified_fold);
                                                                                        ^
In file included from /home3/Software/DSI_studio/src/tipl/tipl.hpp:83:0,
                 from /home3/Software/DSI_studio/src/connectometry/nn_connectometry_analysis.h:6,
                 from /home3/Software/DSI_studio/src/connectometry/nn_connectometry_analysis.cpp:1:
/home3/Software/DSI_studio/src/tipl/ml/cnn.hpp:704:6: note: candidate: template<class label_type> void tipl::ml::data_fold_for_cv(const tipl::ml::network_data<label_type>&, std::vector<tipl::ml::network_data_proxy<label_type> >&, std::vector<tipl::ml::network_data_proxy<label_type> >&, int)
 void data_fold_for_cv(const network_data<label_type>& rhs,
      ^~~~~~~~~~~~~~~~
/home3/Software/DSI_studio/src/tipl/ml/cnn.hpp:704:6: note:   template argument deduction/substitution failed:
/home3/Software/DSI_studio/src/connectometry/nn_connectometry_analysis.cpp:204:88: note:   candidate expects 4 arguments, 5 provided
         tipl::ml::data_fold_for_cv(fp_data,train_data,test_data,cv_fold,stratified_fold);`

**Comment by frankyeh** [comment]
I committed an update to TIPL and it should work now.
Frank

**Comment by DoctorYe** [comment]
Thank you!
