### ISSUE TITLE
Converting DSI to HARDI

### ISSUE THREAD

**Issue by soichih** [frankyeh/DSI-Studio#39]
Hello! I am trying to find a command line tool that can convert a DSI scheme dwi image (dwi/bvecs/bvals) into HARDI scheme.

I have reached here via this article
> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5021685/#B30

It mentions..

```
.. routine was implemented in DSI Studio (http://dsi-studio.labsolver.org), a publicly available and open source tool. The source code for scheme conversion can be found at https://github.com/frankyeh/DSI-Studio (search for “SchemeConverter”).
```

I've searched for SchemeConverter, but I am not sure how to go about pulling the SchemeConverter class out of this repo and successfully compiling them, and using them as a command line tool. Is it even possible? Or do you know of a better tools that is more suitable for this purpose?

Thank you!

**Comment by frankyeh** [comment]
The code has been removed, but you can find it in the older version of the
source code.

However, if you know how to code in MATLAB or Python, the computation is
fairly simple.

The conversion will be just one or two lines of code (see eq.4 of the
paper).

Best,
Frank

**Comment by soichih** [comment]
Frank,

Thank you for the pointer. I know python, but unfortunately, eq.4 is beyond my ability to comprehend. If you could help me translate it to python code, I can turn it into a web service that runs on brainlife.io so that other people can run it and use it to replicate your findings and/or do other experienments. Would you be interested?

Thank you for your assistance!
Soichi

**Comment by frankyeh** [comment]
Here's the code for building the A matrix:

http://dsi-studio.labsolver.org/Manual/Reconstruction#TOC-Optional:-Reconstruction-Using-MATLAB

The code fragment
"sinc(odf_vertices'*b_vector*mean_diffusion_distance_ratio/pi)" is the
A matrix.

Once you have the A matrix, the rest is just a simple matrix multiplication.

Hope this helps.
Frank

**Comment by mattcieslak** [comment]
You can also use this https://qsiprep.readthedocs.io/en/latest/reconstruction.html#csdsi-3dshore to convert DSI to an ABCD or HCP multishell scan.

**Comment by frankyeh** [comment]
like [pressed]
