### ISSUE TITLE
Building a connectometry database - it worked without OFDFs?

### ISSUE THREAD

**Issue by andregouws** [frankyeh/DSI-Studio#46]
Hi Frank -
( I hope you are well in these testing times. I also understand that people have other priorities at the moment so I'm not expecting an answer soon - I'll be raising a few query tickets so please look at them only when its convenient)

We have built  a connectometry database. After starting to play with it we realised we needed to do a bit more reading about the ins and outs of using it - of course we should have done that before. So a few questions have arisen. 

The tutorials say that, when running QSDR reconstruction we should use the "save ODF" option because this is needed for connectometry analyses later. We missed this first time round - I am concerned that we were however able to run the "construct a connectometry database" command from the gui on those inputs that didn't have the ODFs saved in them. Is that supposed to happen? Also, that database is likely to be wrong then, correct?

I am currently re-running the QSDR reconstruction with the --record_odf=1 flag and am getting outputs that are about 10x bigger than the previous ones, so I think that is working. (I can also see the ODFs in the data viewer now which I couldn't before).

I will try to build a database from the new data shortly . Please let me know if we are doing sensible things or not.

Thanks for your help

Andre'

**Comment by frankyeh** [comment]
>
>
> The tutorials say that, when running QSDR reconstruction we should use the
> "save ODF" option because this is needed for connectometry analyses later.
> We missed this first time round - I am concerned that we were however able
> to run the "construct a connectometry database" command from the gui on
> those inputs that didn't have the ODFs saved in them. Is that supposed to
> happen? Also, that database is likely to be wrong then, correct?
>

Not really, without ODF, the measurements you can extract are gong to be
limited to voxel-based metrics (e.g. FA, md...etc). The database can still
work, but it will miss an potentially important pieces (the "qa").
