### ISSUE TITLE
Error using singularity: 'FATAL: no executable dsi_studio found'

### ISSUE THREAD

**Issue by jnecus** [frankyeh/DSI-Studio#48]
Hello, 

I posted this on website discussion but wasn't sure whether that forum is still in use. Sorry for the repost if so.

I am trying execute command line dsi_studio via singularity. I have pulled the singularity file but when running the lines below I get the following error:

```
singularity pull docker://dsistudio/dsistudio
singularity exec dsistudio_latest.sif dsi_studio --action=rec --source=my.src.gz --thread_count=4 --method=7 --param0=1.7  #command line

```

> WARNING: passwd file doesn't exist in container, not updating
> WARNING: group file doesn't exist in container, not updating
> FATAL:   no executable dsi_studio found

**Comment by frankyeh** [comment]
https://github.com/hpcng/singularity/issues/2737

**Comment by jnecus** [comment]
This has been resolved. It was a local cluster issue with Singularity. Thanks for the reply, Frank.
