### ISSUE TITLE
Make docker container available for Windows

### ISSUE THREAD

**Issue by JohannesWiesner** [frankyeh/DSI-Studio#49]
On the [download page ](http://dsi-studio.labsolver.org/dsi-studio-download)it says:

>      LINUX 
>      DSI Studio can run on Linux by using docker container or singularity
> 
>   docker image: docker://dsistudio/dsistudio
>  
> docker run -ti --rm -e DISPLAY=$DISPLAY \
>                     -v /tmp/.X11-unix:/tmp/.X11-unix \
>                     -v $PWD:/data \
>                     dsistudio/dsistudio:latest 

However, I would like to use Docker on Windows (my local laptop) just to try out a DSI-Studio-Pipeline on one or two dummy subjects. Are there plans to also implement a working container that works also on Windows?

**Comment by frankyeh** [comment]
The same container should also work on Windows.

**Comment by JohannesWiesner** [comment]
Ah okay...I got confused by `-e DISPLAY=$DISPLAY` and the mount-flag `-v /tmp/.X11-unix:/tmp/.X11-unix`. How is that working on my Windows machine since there is no `$DISPLAY` and `/tmp/.X11-unix`?

**Comment by frankyeh** [comment]
The setting on Windows may be different:
https://docs.docker.com/docker-for-windows/install/
but the container file should be the same.
