### ISSUE TITLE
Implement --output for dsi_studio --action=qc

### ISSUE THREAD

**Issue by JohannesWiesner** [frankyeh/DSI-Studio#50]
It would be nice if it would be possible to specify an output directory for the `qc` operation just like for `dsi_studio --action=src`

```
dsi_studio --action=qc --source=my.src.gz --output=/foo/bar/my.qc.txt
```

**Comment by frankyeh** [comment]
Thank you for the suggestion. I am listing this on the to-do list.
Frank

**Comment by frankyeh** [comment]
This feature is implemented. Please give it a try and see if it works.

Best regards,
Frank
