### ISSUE TITLE
Implement --output for dsi_studio --action=rec

### ISSUE THREAD

**Issue by JohannesWiesner** [frankyeh/DSI-Studio#52]
Similar to #50, it would also be useful it it was possible to specify an output directory for the reconstruction. Reason: It would be nice, if the outputs for --src, --rec, --trk all could have their own output directories. That would make it a bit more handy to structure the whole DSI-Studio Process.

**Comment by frankyeh** [comment]
I will implement this and let you know once available.
Frank

**Comment by frankyeh** [comment]
This feature is implemented. You can now assign output directory using
--output with src rec trk ana
If anything does not work as expected, please let me know.
Best regards,
Frank

**Comment by JohannesWiesner** [comment]
Hi Frank,

Awesome, thank you very much! I'll download the latest docker image and let you know if everything works :)

Greetings,

Johannes
