### ISSUE TITLE
Problem with OpenGL while running fibre visualisation in singularity container

### ISSUE THREAD

**Issue by k-bingcai** [frankyeh/DSI-Studio#54]
Hi there,

Thanks for the amazing work that has been put into dsistudio. Really appreciate it. 

I have been running into an issue with the OpenGL library when trying to run fibre visualisation (i.e. step 3) with singularity in a HPC environment. This seems to be very much related to the issue brought up here: https://github.com/frankyeh/TIPL/issues/10. I've tried to implement the suggested solutions but to no avail. Does anyone know of any newer fix?

**Comment by frankyeh** [comment]
It seems that there is no universal solution to this issue, but I will
keep tracking this problem and hopefully identify a workaround.

Best,
Frank
