### ISSUE TITLE
Not sure which threshold is used and if its value is randomly chosen or not

### ISSUE THREAD

**Issue by JohannesWiesner** [frankyeh/DSI-Studio#55]
I am using `dsi_studio --action=trk` without any input for `fa_treshold`. [According to the docs](http://dsi-studio.labsolver.org/Manual/command-line-for-dsi-studio) this means that

> If fa_threshold  is not assigned, then the default Otsu's threshold will be used

which (again according to the docs) should equal `0.6` by default. However, when I load my `.fib` file into DSI Studio and add the resulting `.tt` to it, I get the following information about the `.tt` file in the lower right corner of the UI:

>  A deterministic fiber tracking algorithm (Yeh et al., PLoS ONE 8(11): e80713, 2013) was used. A seeding region was placed at whole brain. **The anisotropy threshold was randomly selected**. The angular threshold was 55 degrees. The step size was 1 mm. Tracks with length shorter than 10 or longer than 400 mm were discarded. A total of 100000 tracts were calculated. parameter_id=c9A99193FE8D5123Fb803Fcb2041bC843A08601ca01cbaCDCC4C3Ec 

Is this just misleading information derived from the `.tt` file or did DSI Studio really chose the threshold randomly during fiber tracking? If I don't specify `fa_threshold`, then `otsu_treshold` with a value of `0.6` should be chosen? Why does "_The anisotropy threshold was randomly selected_" sentence then appear in the UI?

**Comment by frankyeh** [comment]
Sorry for my inaccurate description (I am correcting them now).

If fa_threshold is not assigned, DSI Studio will use 0, which selects a
value between [0.5 Otsu, 0.7 Otsu] using a uniform distribution.

Best regards,
Frank

**Comment by JohannesWiesner** [comment]
Hi Frank, thanks so much, now it's more clear what DSI Studio is doing behind the scenes :) Feel free to close this issue!
