### ISSUE TITLE
DSI-Studio with singularity: --source file does not exist

### ISSUE THREAD

**Issue by dubergonzoni** [frankyeh/DSI-Studio#57]
Dear Dr Frank Yeah,

I'm trying to run the code below:

singularity exec /usr/local/dsistudio/dsistudio.simg dsi_studio --action=ana --source=/usr/local/Lesion_Quantification_Toolkit/Support_Tools/Tractography_Atlas/HCP842_1mm.fib.gz --tract=/usr/local/Lesion_Quantification/Support_tools/Tractography_Atlas/all_tracts_1mm.trk.gz --output=out_file --connectivity=cfg.parcel_path --connectivity_type=cfg.con_typ --connectivity_threshold=0 --export=tdi

But I'm getting this error:

DSI Studio Mar 20 2021, Fang-Cheng Yeh
source=/usr/local/Lesion_Quantification_Toolkit/Support_Tools/Tractography_Atlas/HCP842_1mm.fib.gz
action=ana
loading /usr/local/Lesion_Quantification_Toolkit/Support_Tools/Tractography_Atlas/HCP842_1mm.fib.gz...
/usr/local/Lesion_Quantification_Toolkit/Support_Tools/Tractography_Atlas/HCP842_1mm.fib.gz does not exist. terminating...
Warning: --tract is not used. Please check command line syntax.
Warning: --output is not used. Please check command line syntax.
Warning: --connectivity is not used. Please check command line syntax.
Warning: --connectivity_type is not used. Please check command line syntax.
Warning: --connectivity_threshold is not used. Please check command line syntax.
Warning: --export is not used. Please check command line syntax.

I can't find what I'm doing wrong. Why it's saying the file does not exist it is in the folder?
Can you help me, please?

**Comment by frankyeh** [comment]
Sorry for my late reply.
You may try placing HCP842_1mm.fib.gz in another directory to rule out the
access problem.
Frank
