### ISSUE TITLE
DSI Studio Docker Image - QWidget Error During Tracking

### ISSUE THREAD

**Issue by pcamach2** [frankyeh/DSI-Studio#58]
There seems to be an error with the latest Docker image of DSI Studio, in which the following tracking command

`docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $PWD:/data dsistudio/dsistudio:latest dsi_studio --action=trk --source=/data/dti_src.src.gz.gqi.1.25.fib.gz --seed_count=1000000 --track_id=Arcuate_Fasciculus_L --output=/data/99_test_TRACK.nii.gz`

produces an error with QWidget creation:

```
DSI Studio Jun  8 2021, Fang-Cheng Yeh
source=/data/dti_src.src.gz.gqi.1.25.fib.gz
action=trk
loading /data/dti_src.src.gz.gqi.1.25.fib.gz...
otsu_threshold=0.6
fa_threshold=0
dt_threshold=0.2
turning_angle=0
step_size=0
smoothing=0
min_length=30
max_length=300
method=0
initial_dir=0
interpolation=0
seed_plan=0
random_seed=0
check_ending=0
tip_iteration=16
seed_count=1000000
thread_count=24
Consider using --action=atk for automatic fiber tracking
loading /opt/dsi-studio/dsi_studio_64/track/HCP1065.tt.gz
warping atlas tracks to subject space
running normalization
QWidget: Cannot create a QWidget without QApplication
```
I am unsure what change from the prior Docker image is now causing this error. 

Thanks in advance for your help!

**Comment by frankyeh** [comment]
Thank you for reporting this issue. I committed a code revision and
please see if it works for you.

Feel free to let me know if it still doesn't work.

Best regards,
Frank

**Comment by pcamach2** [comment]
Hi Frank,

Thank you! I pulled the updated Docker image and the code revision has resolved the error.

Cheers,
Paul

**Comment by frankyeh** [comment]
Glad to know it works!
Frank
