### ISSUE TITLE
Writing network_measures to structure

### ISSUE THREAD

**Issue by JohannesWiesner** [frankyeh/DSI-Studio#61]
I stumbled upon this [thread on google groups ](https://groups.google.com/g/dsi-studio/c/rq2FJRvtE6I/m/Pcd9Pc7VAwAJ) because I am facing the same problem. It would be nice if network measures could be exported in a structured form (.mat, .json, etc.). Since the question is already 3 years I wonder if this has been implemented in the meantime?

**Comment by frankyeh** [comment]
I am sorry that there is still no .mat .jason output.
My solution is to write a text reader in MATLAB or python.
It seems to only need few lines of code to complete the task.

**Comment by JohannesWiesner** [comment]
No worries! :) I just wanted to make sure that I haven't overseen something :) Alright, I will write a python script then to parse the `*network_measures.txt` into a python dictionary or `.json` file

**Comment by JohannesWiesner** [comment]
Just for completeness - here's my code (could probably be optimized but does what it is supposed to do):

```python
def isFloat(string):
    try:
        float(string)
        return True
    except ValueError:
        return False

with open('571144.src.gz.hcp1065.qsdr.1.25.R73.fib.gz.tt.gz.HCP-MMP.ncount.end.network_measures.txt') as f:
    network_measures = [e.split() for e in f.readlines()]
    network_measures = {l[0]:l[1:] for l in network_measures}

    for k,l in network_measures.items():
        if len(l) == 1:
            network_measures[k] = float(l[0])
        elif len(l) > 1:
            network_measures[k] = [float(e) if isFloat(e) else e for e in l]

```

**Comment by frankyeh** [comment]
Thanks a lot!
I believe many users will find this very helpful.
Frank

**Comment by mattcieslak** [comment]
If this would be helpful, here is the function used in qsiprep: https://github.com/PennLINC/qsiprep/blob/master/qsiprep/interfaces/dsi_studio.py#L427

**Comment by frankyeh** [comment]
Thanks! Wish I have come across this code earlier.
I will create a link in the documentation.
Frank
