### ISSUE TITLE
Committing package files is bad practice for git

### ISSUE THREAD

**Issue by gdevenyi** [frankyeh/DSI-Studio#62]
The files here,
https://github.com/frankyeh/DSI-Studio/tree/master/packages

Should be attached here: https://github.com/frankyeh/DSI-Studio/releases instead.

Committing package files into git makes downloads huge, as a git clone will require downloading of every package file ever committed.

One possible solution
https://www.phase2technology.com/blog/removing-large-files-git-bfg

**Comment by frankyeh** [comment]
Thank you for the suggestion. I am going to remove the packages.

**Comment by frankyeh** [comment]
packages removed. 
Much appreciated for the suggestions.
