### ISSUE TITLE
Update to std::filesystem breaks compilation on ubuntu 18.04

### ISSUE THREAD

**Issue by gdevenyi** [frankyeh/DSI-Studio#63]
The version of qt on 18.04 is 5.9.5 which is not c++-17 compatible.

**Comment by gdevenyi** [comment]
Nevermind. Its because the whole thing doesn't work below 5.12.

**Comment by frankyeh** [comment]
I revised the DSI Studio code and will use g++9 in the future to
ensure better C++17 compatibility.
Frank
