### ISSUE TITLE
failure of the autotrack feature

### ISSUE THREAD

**Issue by drobwolf** [frankyeh/DSI-Studio#67]
Hi, thanks for your fantastic work! I'm running into an issue with some reconstructions using the autotrack feature in the CLI in which it generates only a file ending in "no_result.txt", but no error messages are generated in stderr and everything in stdout looks good...i'm not sure where to begin debugging. I saw from your autotrack code that this can happen either when a file by that name is already present and overwrite is set to off, or when there are "too low yield" of fibers due to quality issues...but I don't believe either of those is occurring in my case.

**Comment by frankyeh** [comment]
Have you done a quality check on your data?
http://dsi-studio.labsolver.org/Manual/Parse-DICOM#TOC-Batch-Quality-Control-for-SRC-files

Also, I would suggest updating DSI Studio again and see if that works.

If still doesn't work, please send me an SRC file, and I will help check
the problem for you.

Best regards,
Frank

**Comment by drobwolf** [comment]
Thanks for the quick reply! When I qc using the CLI, I get the following:

Fiber coherence index: 6251.8                                              
Fiber incoherent index: 37335.6  

Just the two numbers for each file. I'm wondering whether this might be due to the fact that my "source" files are all "fib.gz"?

**Comment by frankyeh** [comment]
Yes, please assign SRC files and see if it works.
Frank

**Comment by drobwolf** [comment]
so i dont seem to have src files for these subjects. their fib.gz files were generated prior to my joining the lab using the qsiprep pipeline. id be happy to send a fib.gz file but github wont seem to attach it (it is around 400 mb), so ive included a google drive link 
https://drive.google.com/file/d/1JQ4OdfL4wjLYSDi1I7GCzfX8skFp1W6H/view?usp=drivesdk

**Comment by frankyeh** [comment]
I checked the data in detail, and there is bad news. The b-table has a
problem.

Please check the cingulum in detail (highlighted) and you will see the
fiber orientation is slightly rotated downward. A likely cause is that the
images were resampled to align AC-PC, but the b-table was not rotated
accordingly. The preprocessing step has to be corrected.

The only solution is to start from the raw data and re-process them from
the bottom-up (even the SRC files need to be re-created).

I am sorry about this, but tracking will not work out unless a correct
table was used.

Best regards,
Frank

[image: image.png]

**Comment by drobwolf** [comment]
Thanks again for looking into this so quickly. The image you referenced in your reply somehow didn't come through for me, could you try re-sending/re-attaching it?

**Comment by frankyeh** [comment]
![image](https://user-images.githubusercontent.com/275569/126783047-0444f80f-561b-440a-8ad2-b65a1d248efc.png)

**Comment by mattcieslak** [comment]
@drobwolf did you create these with the `dsistudio_gqi` pipeline from qsiprep? If not and you tried to use dsi studio's most recent release directly DSI Studio will interpret the bvecs incorrectly. You'll need to use a flag that tells DSI Studio to interpret bvecs how it used to circa early 2020 (I forget flag offhand)

**Comment by frankyeh** [comment]
It is --flip_by=1

**Comment by drobwolf** [comment]
Thank you both for your very helpful comments! We re-ran qsiprep using v 0.14. I then subsequently ran dsistudio within a singularity sif (pulled since may 2021) with the following syntax: 

bvec=$(echo *.bvec) && bval=$(echo *.bval) && source=$(echo *dwi.nii.gz) && singularity exec ~/software/dsistudio_latest.sif dsi_studio --action=atk --source=$source --bval=$bval --bvec=$bvec --flip_by=1

However I am still failing to track some files, resulting in stat files that end in '*no_result.txt'.

Below I have included a link to a Dropbox folder with the files needed to reproduce this problem. I'm wondering whether you both could take a look when you have the time to do so?

Best,
Doug wolfe

https://www.dropbox.com/sh/xcbz4jlydo32duw/AAB5i-fuzRqP2itlK4uelVSIa?dl=0

**Comment by frankyeh** [comment]
Hi Doug,

    You may check this out:
http://dsi-studio.labsolver.org/Manual/automatic-fiber-tracking#TOC-Troubleshooting

    If "no result" happens quite often (e.g. > 50%), then there is a
quality issue (e.g., b-table flipped) that needs to be corrected.

    If it happens occasionally (e.g. < 5%) for some smaller pathways (e.g.,
right AF, SLF I...etc.), then it is likely that your data acquisition is
not good enough (check if data have any of the conditions listed in the
documentation).

Best,
Frank

**Comment by frankyeh** [comment]
Just revised the document a few seconds ago. Hope this helps.
