### ISSUE TITLE
Cannot find file error

### ISSUE THREAD

**Issue by alexamousley** [frankyeh/DSI-Studio#72]
Hello,

I am running DSI studio via singularity and I keep getting an error that it cannot find a file. I have double-checked that it is the correct path. I have also tried it with just the file name instead of the whole path, but the same error occurs.

Here is what the slurm.out file looks like:
`DSI Studio "Chen" Apr  5 2022
source=/imaging/astle/am11/dHCP/red_test/qsirecon/sub-NDA/dwi/sub-NDA_space-T1w_desc-preproc_gqi.fib.gz
action=atk
track_id=Fasciculus,Cingulum,Aslant,Corticos,Thalamic_R,Reticular,Optic,Fornix,Corpus
target tracks: Arcuate_Fasciculus_L Arcuate_Fasciculus_R Cingulum_Frontal_Parahippocampal_L Cingulum_Frontal_Parahippocampal_R Cingulum_Frontal_Parietal_L Cingulum_Frontal_Parietal_R Cingulum_Parahippocampal_Parietal_L Cingulum_Parahippocampal_Parietal_R Cingulum_Parahippocampal_L Cingulum_Parahippocampal_R Cingulum_Parolfactory_L Cingulum_Parolfactory_R Frontal_Aslant_Tract_L Frontal_Aslant_Tract_R Inferior_Fronto_Occipital_Fasciculus_L Inferior_Fronto_Occipital_Fasciculus_R Inferior_Longitudinal_Fasciculus_L Inferior_Longitudinal_Fasciculus_R Middle_Longitudinal_Fasciculus_L Middle_Longitudinal_Fasciculus_R Parietal_Aslant_Tract_L Parietal_Aslant_Tract_R Superior_Longitudinal_Fasciculus1_L Superior_Longitudinal_Fasciculus1_R Superior_Longitudinal_Fasciculus2_L Superior_Longitudinal_Fasciculus2_R Superior_Longitudinal_Fasciculus3_L Superior_Longitudinal_Fasciculus3_R Uncinate_Fasciculus_L Uncinate_Fasciculus_R Vertical_Occipital_Fasciculus_L Vertical_Occipital_Fasciculus_R Corticospinal_Tract_L Corticospinal_Tract_R Corticostriatal_Tract_Anterior_L Corticostriatal_Tract_Anterior_R Corticostriatal_Tract_Posterior_L Corticostriatal_Tract_Posterior_R Corticostriatal_Tract_Superior_L Corticostriatal_Tract_Superior_R Thalamic_Radiation_Anterior_L Thalamic_Radiation_Anterior_R Thalamic_Radiation_Posterior_L Thalamic_Radiation_Posterior_R Thalamic_Radiation_Superior_L Thalamic_Radiation_Superior_R Fornix_L Fornix_R Optic_Radiation_L Optic_Radiation_R Reticular_Tract_L Reticular_Tract_R Corpus_Callosum_Forceps_Minor Corpus_Callosum_Body Corpus_Callosum_Tapetum Corpus_Callosum_Forceps_Major
thread_count=32
export_template_trk=1
default_mask=0
overwrite=0
export_trk=1
export_stat=1
tip=32
track_voxel_ratio=2
tolerance=16,18,20
length_ratio=1.25
automatic fiber tracking
sub-NDA_space-T1w_desc-preproc_gqi
processing sub-NDA_space-T1w_desc-preproc_gqi
ERROR:cannot find file:/imaging/astle/am11/dHCP/red_test/qsirecon/sub-NDA/dwi/sub-NDA_space-T1w_desc-preproc_gqi.fib.gz`

Any advice on what may be going wrong? Thanks in advance!

Best,
Lexi

**Comment by frankyeh** [comment]
Sorry for the late reply. I am moving this issue to https://groups.google.com/g/dsi-studio/c/HV9qqc3TZ9E
