### ISSUE TITLE
Get version number without launching GUI

### ISSUE THREAD

**Issue by dmd** [frankyeh/DSI-Studio#73]
Is there a way to get the version number *without launching the GUI*?

**Comment by frankyeh** [comment]
You can call the command line to get it.
DSI Studio uses the date as the version, so the file date of the executive
is also the version.
Frank

**Comment by dmd** [comment]
What am I missing? If I run without a `$DISPLAY`, I get:

$ singularity run /data/singularity-images/dsistudio_latest.sif dsi_studio
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

[1]    35194 abort      singularity run /data/singularity-images/dsistudio_latest.sif dsi_studio

$

**Comment by frankyeh** [comment]
dsi_studio --action=qc --source=.

**Comment by frankyeh** [comment]
Sure. on my to-do list now.

**Comment by frankyeh** [comment]
DSI Studio updated to provide this function.
Build status: https://github.com/frankyeh/DSI-Studio/actions/runs/3211602576
