### ISSUE TITLE
Mark tracts on T1W with colors

### ISSUE THREAD

**Issue by Shade-** [frankyeh/DSI-Studio#75]
Hello,
thank you for this amazing piece of software. Makes tractography so much easier.
I have succeeded creating my tract and I've used the [Slices] > [Mark tracts on slices] feature to print the tract on my T1w and export it as DICOM. This allows me to load my tracks on the StealthStation S7 we are using in the OR, with awesome results.

My question is, can we mark tracts with different colors so we can distinguish them onto T1w? Thank you!

**Comment by frankyeh** [comment]
The raw T1w DICOM is grayscale. The navigation software may have a way to
color.
Frank

**Comment by Shade-** [comment]
Thanks! I was able to play with the threshold on the navigation system and got a nice 3D model of my tract.
