### ISSUE TITLE
Can't load more than 240 dicoms

### ISSUE THREAD

**Issue by Shade-** [frankyeh/DSI-Studio#76]
Following #75, I have tried to mark other tracks onto different subjects. Found out that DSI Studio fails to load more than 240 DICOM images (using [Slices] > [Insert other images...]); fails at the 241st one. One of my subjects has a 320-images volumetric T1. Tested this by loading them all (says the 241st image fails), then just chunks (40-to-200 for example), the latter works.

For context, I have converted my Siemens DICOM folder with DSI Studio itself (Batch processing > Rename DICOM folders).

**Comment by frankyeh** [comment]
Thank you for reporting.
I will work out a code review to see if I can find out the bug.
Frank

**Comment by Shade-** [comment]
Thanks. In the meantime I've been exporting images as nifti, then load them in Slicer, readjust the image intensity and finally export the nifti as DICOM. Dont mind the extra steps as they work just fine but a direct one-click command to export as DICOM is ideal.

**Comment by frankyeh** [comment]
Hi Filippo,

    I have done the code review but still could not find out the bug. Is it
possible to send me the 320 volume T1W DICOM?

Thanks again for your help,
Frank

**Comment by Shade-** [comment]
Sorry for the late reply, I will send you a sample T1W soon. With a recent upgrade in our hardware to the ES8, which can read Nifti files, this has become easier.
