### ISSUE TITLE
--to_src_nii option doesn't work in cli

### ISSUE THREAD

**Issue by mapseamoff** [frankyeh/DSI-Studio#77]
Hello!

I just updated DSI Studio from version 10.08.22 to 13.02.23 and noticed that the following command:
`./dsi_studio --action=ren --source=/path/to/src --output=/path/to/out --to_src_nii=1`
doesn't produce nii/src files.

This still works from GUI, but I prefer batch processing. Am I missing something? Or is it possible to get access to older binary release?

Many thanks!

**Comment by frankyeh** [comment]
I am fixing it and will let you know once it is done.
Thanks for reporting this issue.
Frank

**Comment by frankyeh** [comment]
Updated. Please see if the new version works for you.
Thanks for reporting the problem.
Frank

**Comment by mapseamoff** [comment]
Many thanks! It works now
