### ISSUE TITLE
Is Nvidia Tesla V100 supported in a VDI context?

### ISSUE THREAD

**Issue by simoneeu** [frankyeh/DSI-Studio#81]
Hi,
I'm preparing a VM for a Virtual Lab on Microsoft Azure, with a discrete GPU, NVidia Tesla V100 with 16gb of dedicated RAM.
I have installed latest Nvidia official driver, VC package and also Cuda Toolkit but DSI-Studio can't load a Fib.gz file.
Step T3: Fiber Tracking & Visualization is the function I need to use but it crashes.
Event viewer reports that Qt6gui.dll 6.2.0.0 crash and that's all.
What can I do?
Thanks a lot
Simone

**Comment by frankyeh** [comment]
It seems to be a problem with the OpenGL.
DSI Studio initiates OpenGL when creating the GUI. It may crash if the
opengl functions is not working.
Hope this helps,
Frank

**Comment by simoneeu** [comment]
Thank you Frank, I will investigate now on the OpenGL part in Windows 10.
Do you know if exist a service or something similar that have to startup before use Dsi-Studio?
Thank you
Simone

**Comment by frankyeh** [comment]
I don't think so.
Frank
