### ISSUE TITLE
DSI Studio-Version differences

### ISSUE THREAD

**Issue by arefks** [frankyeh/DSI-Studio#82]
**Describe the bug**
What we do:

1-Loading a fiber tract file with the following naming scheme: (SubjecName.fib.gz) 
2- Loading the corresponding atlas of that subject in the form of SubjectName_split_scaled.nii.gz

**Situation 1:**
Windows 11
DSI studio Version: Juli 2023
Step 1: Works ✅
Step 2: Does no work ❌ (Loads a whole brain mask, not segmented regions)
![image](https://github.com/frankyeh/DSI-Studio/assets/87692940/90a66562-d5c0-4b07-95a8-bb95e6d4b7f9)

**Situation 2:**
Windows 11
DSI studio Version: August 2022
Step 1: Works ✅
Step 2: Does not work completely ✅ 
![image](https://github.com/frankyeh/DSI-Studio/assets/87692940/089e2a1e-e863-4bc2-b513-176fac050f20)

@lucaruthe 
@VictorVeraFrazao
@maswendt

**Comment by frankyeh** [comment]
DSI Studio is updated to handle this problem.
Could you download the new version and see if it works?

**Comment by lucaruthe** [comment]
It is working now. Thank you!
