### ISSUE TITLE
How can these metrics be extracted to generate nii files?

### ISSUE THREAD

**Issue by Luoyu-Wang** [frankyeh/DSI-Studio#87]
Hi! I have upgraded to the latest version of the software and used the --other_output=all option, but it did not generate any metrics. These images seem to be contained in fib files, how can these metrics be extracted to generate nii files?

**Comment by frankyeh** [comment]
Could you post the complete command used and the output from the command
line during the reconstruction?
Frank

**Comment by Luoyu-Wang** [comment]
Thanks Frank, here is the command line and output:
dsi_studio --action=rec --source=DwiImgDenDegUEddyPyDesignerSRC/*.src.gz --method=4 --output=ParametersDwiDSIStudioSRCFIB/ --other_ output=all --thread_count=16 --param0=1.5 --csf_calibration=1

S0001.src.gz.gqi.1.5.fib.gz
S0002.src.gz.gqi.1.5.fib.gz
...

**Comment by frankyeh** [comment]
You may add > log.txt to redirect the console output and post them here.
Frank

**Comment by Luoyu-Wang** [comment]
OK, here is the log.txt
[1;34mDSI Studio version: Chen"陳" Mar 29 2024[0m
| cannot obtain GPU driver and device information (CUDA ERROR 35). please update the Nvidia driver and install CUDA Toolkit.
| [0;33mDSI Studio version[0m: Chen"陳"
| [0;32maction[0m=rec
| [0;32msource[0m=DwiImgDenoiseDegibbsUEddyPyDesignerSRC/*.src.gz
| [0;32mloop[0m=DwiImgDenoiseDegibbsUEddyPyDesignerSRC/*.src.gz
|-[1;34mprocessing loop[0m
| | a total of 2 files found
| | [0;32mloop_thread[0m=1
| | DwiImgDenoiseDegibbsUEddyPyDesignerSRC/*.src.gz->DwiImgDenoiseDegibbsUEddyPyDesignerSRC/S0001.src.gz
| | [0;32mloop[0m=
| | [0;32maction[0m=rec
| |-[1;34mrun rec[0m
| | | [0;32msource[0m=DwiImgDenoiseDegibbsUEddyPyDesignerSRC/S0001.src.gz
| | |-[1;34mopen SRC file S0001.src.gz[0m
| | | | generating mask
| | | |_1.117 s
| | |-[1;34mreconstruction parameters[0m
| | | | [0;32mmethod[0m=4
| | | | [0;32modf_resolving[0m=0
| | | | [0;32mrecord_odf[0m=0
| | | | [0;32mdti_no_high_b[0m=1
| | | | [0;32mother_output[0m=all
| | | | [0;32mr2_weighted[0m=0
| | | | [0;32mthread_count[0m=16
| | | | [0;32mparam0[0m=1.5
| | | | [0;32mparam1[0m=3000
| | | | [0;32mparam2[0m=0.05
| | | | [0;33mtemplate 0[0m: "ICBM152_adult.QA.nii"
| | | | [0;33mtemplate 1[0m: "C57BL6_mouse.QA.nii"
| | | | [0;33mtemplate 2[0m: "dHCP_neonate.QA.nii"
| | | | [0;33mtemplate 3[0m: "INDI_rhesus.QA.nii"
| | | | [0;33mtemplate 4[0m: "Pitt_marmoset.QA.nii"
| | | | [0;33mtemplate 5[0m: "WHS_SD_rat.QA.nii"
| | | | [0;32mtemplate[0m=0
| | | |_1 ms
| | | [0;32mmotion_correction[0m=0
| | |-[1;34madditional processing steps[0m
| | | | [0;32mcheck_btable[0m=0
| | | |_0 ms
| | | [0;32moutput[0m=ParametersDwiDSIStudioSRCFIB1/
| | |-[1;34minitializing[0m
| | | | 11ReadDWIData
| | | | 10Dwi2Tensor
| | | | 13BalanceScheme
| | | | 9GQI_Recon
| | | | 9RDI_Recon
| | | | 11SaveMetrics
| | | |_41 ms
| | |-[1;34mGQI[0m
| | | |_3.836 s
| | |-[1;34moutput[0m
| | | | 11ReadDWIData
| | | | 10Dwi2Tensor
| | | | 13BalanceScheme
| | | | 9GQI_Recon
| | | | 9RDI_Recon
| | | | 11SaveMetrics
| | | |_854 ms
| | | [0;33mFIB file saved[0m: ParametersDwiDSIStudioSRCFIB1//S0001.src.gz.gqi.1.5.fib.gz
| | |_5.87 s
| | DwiImgDenoiseDegibbsUEddyPyDesignerSRC/*.src.gz->DwiImgDenoiseDegibbsUEddyPyDesignerSRC/S0002.src.gz
| | [0;32mloop[0m=
| | [0;32maction[0m=rec
| |-[1;34mrun rec[0m
| | | [0;32msource[0m=DwiImgDenoiseDegibbsUEddyPyDesignerSRC/S0002.src.gz
| | |-[1;34mopen SRC file S0002.src.gz[0m
| | | | generating mask
| | | |_1.105 s
| | |-[1;34mreconstruction parameters[0m
| | | | [0;32mmethod[0m=4
| | | | [0;32modf_resolving[0m=0
| | | | [0;32mrecord_odf[0m=0
| | | | [0;32mdti_no_high_b[0m=1
| | | | [0;32mother_output[0m=all
| | | | [0;32mr2_weighted[0m=0
| | | | [0;32mthread_count[0m=16
| | | | [0;32mparam0[0m=1.5
| | | | [0;32mparam1[0m=3000
| | | | [0;32mparam2[0m=0.05
| | | | [0;33mtemplate 0[0m: "ICBM152_adult.QA.nii"
| | | | [0;33mtemplate 1[0m: "C57BL6_mouse.QA.nii"
| | | | [0;33mtemplate 2[0m: "dHCP_neonate.QA.nii"
| | | | [0;33mtemplate 3[0m: "INDI_rhesus.QA.nii"
| | | | [0;33mtemplate 4[0m: "Pitt_marmoset.QA.nii"
| | | | [0;33mtemplate 5[0m: "WHS_SD_rat.QA.nii"
| | | | [0;32mtemplate[0m=0
| | | |_2 ms
| | | [0;32mmotion_correction[0m=0
| | |-[1;34madditional processing steps[0m
| | | | [0;32mcheck_btable[0m=0
| | | |_0 ms
| | | [0;32moutput[0m=ParametersDwiDSIStudioSRCFIB1/
| | |-[1;34minitializing[0m
| | | | 11ReadDWIData
| | | | 10Dwi2Tensor
| | | | 13BalanceScheme
| | | | 9GQI_Recon
| | | | 9RDI_Recon
| | | | 11SaveMetrics
| | | |_40 ms
| | |-[1;34mGQI[0m
| | | |_3.897 s
| | |-[1;34moutput[0m
| | | | 11ReadDWIData
| | | | 10Dwi2Tensor
| | | | 13BalanceScheme
| | | | 9GQI_Recon
| | | | 9RDI_Recon
| | | | 11SaveMetrics
| | | |_907 ms
| | | [0;33mFIB file saved[0m: ParametersDwiDSIStudioSRCFIB1//S0002.src.gz.gqi.1.5.fib.gz
| | |_5.97 s
| |_11.843 s
|_11.845 s
[1;31mWARNING: --csf_calibration is not used/recognized. Did you mean --motion_correction ?[0m

**Comment by frankyeh** [comment]
you may use the following command to export the metrics:

dsi_studio --action=exp --source=*.fib.gz --export=dti_fa,ad,rd

For a list of metrics that can be exported, you may get the names by
opening a FIB file at GUI (Step T3).

**Comment by Luoyu-Wang** [comment]
Thank you, Frank, I've got the results  based on your advice.. I have a question regarding the FIB file obtained from GQI reconstruction: Are the dti_fa, ad, ra, gfa values based on GQI or are they calculated using DTI?

**Comment by frankyeh** [comment]
gfa is based on GQI, others are based on DTI.

**Comment by Luoyu-Wang** [comment]
Thanks Frank, you solved my problem perfectly!
