### ISSUE TITLE
renamed track_ids

### ISSUE THREAD

**Issue by mattcieslak** [frankyeh/DSI-Studio#89]
Hi Frank! I updated to the latest dsi studio in qsiprep and noticed a couple changes I'd like to check with you.

  1) It looks like the accepted values for --tract_id have changed: https://app.circleci.com/pipelines/github/PennLINC/qsiprep/1737/workflows/fcf5a043-8dcf-4312-afc8-af303eac8847/jobs/19148
  2) Are `rdi`, `rdi0?L` not created by default in GQI anymore? 

Thanks as ever, also the new NDC and DWI Contrast are looking good

**Comment by frankyeh** [comment]
>
>    1. It looks like the accepted values for --tract_id have changed:
>    https://app.circleci.com/pipelines/github/PennLINC/qsiprep/1737/workflows/fcf5a043-8dcf-4312-afc8-af303eac8847/jobs/19148
>
> Yes, the naming convention has changed:
https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152_adult/ICBM152_adult.tt.gz.txt


>
>    1. Are rdi, rdi0?L not created by default in GQI anymore?
>
> They should be created by default, but there will be an additional check
to see if there are multiple b-values. A single b-value DTI cannot provide
a good estimate of RDI.


Best,
Frank

**Comment by mattcieslak** [comment]
Excellent, Thank you!
