### ISSUE TITLE
en.UTF-8 locale in Docker images

### ISSUE THREAD

**Issue by sbashford** [frankyeh/DSI-Studio#90]
When running the following in the dsistudio/dsistudio:chen-2024-08-05 docker image:

`dsi_studio --action=rec --source=*.src.gz` 

I receive an error:

`locale::facet::_S_create_c_locale name not valid`

I think I located the source of the error [here](https://github.com/frankyeh/TIPL/blob/b693b5affd05de16f1b8f38caba271aac835cc1f/po.hpp#L253). When checking which locales are available on the docker image, I get:

```
# locale -a
C
C.UTF-8
POSIX
```

I'm not sure the best way to add en.UTF-8 to the docker image, but one possible solution is via the ```language-pack-en``` package. I'd be happy to submit a PR if you think this is a worthy approach.

**Comment by frankyeh** [comment]
Thanks for reporting this.
I removed the locale code and is building a new release at
https://github.com/frankyeh/DSI-Studio/actions/runs/10357735884

The new version will be dsistudio/dsistudio:hou-2024-08-12

Best regards,
Frank
