### ISSUE TITLE
Cannot read the file

### ISSUE THREAD

**Issue by JeanWhite12** [frankyeh/DSI-Studio#91]
Hello! When i trying to start working with programm i 
encounter with this problem: cannot read the file. No reading privilege or the file does not exist. Can you help me please? i'm new, trying to do this for a 3 hours with multiple programm (convert the DICOM to NIFTI) for DSI studio but it's not working

**Comment by frankyeh** [comment]
I would suggest watching the tutorial videos at https://practicum.labsolver.org/ and also https://www.youtube.com/watch?v=-J8qBMiHQHk
